# Generated by Django 4.0.1 on 2023-08-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stname', models.CharField(max_length=100)),
                ('stroll', models.IntegerField(primary_key=True, serialize=False)),
                ('stbranch', models.CharField(max_length=100)),
                ('styears', models.IntegerField()),
                ('stadress', models.CharField(max_length=100)),
            ],
        ),
    ]
