# Generated by Django 4.0.1 on 2023-08-31 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='styears',
            new_name='styear',
        ),
    ]
